import AuthProvider from "@/context/authProvider"
import "../globals.css";
import { ThemeProvider } from "@/context/themProvider";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthProvider>
      <ThemeProvider>
      <body>{children}</body>
      </ThemeProvider>
      </AuthProvider>
    </html>
  )
}
