import "../globals.css"
import MobileNav from "@/components/MobilNav";
import AuthProvider from "@/context/authProvider";
import { ThemeProvider } from "@/context/themProvider";
import NavBar from "@/components/public/NavBar";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <ThemeProvider>
          <body>
            <NavBar/>
            {children}
            <MobileNav />
          </body>
        </ThemeProvider>
      </AuthProvider>
    </html>
  )
}
